CHAMPION_FILES = Champion.py

gui-cxxflags = -fPIC $(shell python3-config --includes)
gui-ldflags = -s $(shell python3-config --ldflags)

CHAMPION_FILES += interface.cc api.py
-include Makefile-python
